### ISSUE TITLE
UnboundLocalError when signing-in

### ISSUE THREAD

**Issue by lakonis** [loleg/portraitdomain-web#1]
After successfully signing-up, I get this Python error page when signing-in : 
![bug](https://cloud.githubusercontent.com/assets/9479788/6438049/b9688780-c0c5-11e4-8b2b-125c5fd20654.jpg)

**Comment by loleg** [comment]
Sorry about this (in case it is better to apologize 5 years later than never). The project was not maintained in the first place, and this would need additional debugging. Hope you found a suitable platform for your project idea!
